theme: jekyll-theme-slate
show_downloads: true
title: Website Theme Collection
preview_path: https://www.gem-editor.com/gwc/theme
website_theme:
  - name: 1
    desc: Vertical Button
    cssf: Bootstrap 3
    pwfn:
  - name: 1af
    desc: Vertical Button, fixed
    cssf: Bootstrap 3
    pwfn:
  - name: 1at
    desc: Vertical Button, affix
    cssf: Bootstrap 3
    pwfn: 501
  - name: 1bs4
    desc: Vertical Button
    cssf: Bootstrap 4
    pwfn: 511
  - name: 1b4f
    desc: Vertical Button, fixed
    cssf: Bootstrap 4
    pwfn:
  - name: 1b4a
    desc: Vertical Button 2
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2
    desc: Navigation Bar
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2fi
    desc: Navigation Bar, fixed top
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2in
    desc: Navigation Bar, inverted
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2if
    desc: Navigation Bar, inverted, fixed top
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2ia
    desc: Navigation Bar, inverted, affix
    cssf: Bootstrap 3
    pwfn: 500
  - name: 2prm
    desc: Navigation Bar, blue
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2suc
    desc: Navigation Bar, green
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2inf
    desc: Navigation Bar, cyan
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2wrn
    desc: Navigation Bar, yellow
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2dng
    desc: Navigation Bar, red
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2sec
    desc: Navigation Bar, gray
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2drk
    desc: Navigation Bar, dark
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2lit
    desc: Navigation Bar, light
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fprm
    desc: Navigation Bar, fixed-top, blue
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fsuc
    desc: Navigation Bar, fixed-top, green
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2finf
    desc: Navigation Bar, fixed-top, cyan
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fwrn
    desc: Navigation Bar, fixed-top, yellow
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fdng
    desc: Navigation Bar, fixed-top, red
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fsec
    desc: Navigation Bar, fixed-top, gray
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fdrk
    desc: Navigation Bar, fixed-top, dark
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2flit
    desc: Navigation Bar, fixed-top, light
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2fcd
    desc: Navigation Bar, fixed-top, card style
    cssf: Bootstrap 4
    pwfn: 511
  - name: 2cda
    desc: Navigation Bar, card style 2
    cssf: Bootstrap 4
    pwfn: 500
  - name: 2cdsu
    desc: Navigation Bar, slide up
    cssf: Bootstrap 4
    pwfn: 508
  - name: 3
    desc: Scrollspy
    cssf: Bootstrap 3
    pwfn: 501
  - name: 3a
    desc: Scrollspy & Affix
    cssf: Bootstrap 3
    pwfn: 501
  - name: 3b4
    desc: Scrollspy
    cssf: Bootstrap 4
    pwfn: 508
  - name: 3sn
    desc: Scrollspy with Sticky Navbar
    cssf: Bootstrap 4
    pwfn: 508
  - name: 4
    desc: Scrollspy Vertical Menu
    cssf: Bootstrap 3
    pwfn: 501
  - name: 4a
    desc: Scrollspy Vertical Menu 2
    cssf: Bootstrap 3
    pwfn: 501
  - name: 4b
    desc: Scrollspy Vertical Menu 3
    cssf: Bootstrap 3
    pwfn: 501
  - name: 4b4
    desc: Scrollspy Vertical Menu
    cssf: Bootstrap 4
    pwfn: 511
  - name: 5
    desc: Horizontal Menu
    cssf: Bootstrap 3
    pwfn: 501
  - name: w1
    desc: Sidebar
    cssf: W3.CSS
    pwfn: 509
  - name: w1rd
    desc: Sidebar, red
    cssf: W3.CSS
    pwfn: 510
  - name: w1pk
    desc: Sidebar, pink
    cssf: W3.CSS
    pwfn: 510
  - name: w1pu
    desc: Sidebar, purple
    cssf: W3.CSS
    pwfn: 510
  - name: w1dp
    desc: Sidebar, deep purple
    cssf: W3.CSS
    pwfn: 510
  - name: w1in
    desc: Sidebar, indigo
    cssf: W3.CSS
    pwfn: 510
  - name: w1blu
    desc: Sidebar, blue
    cssf: W3.CSS
    pwfn: 510
  - name: w1lb
    desc: Sidebar, light blue
    cssf: W3.CSS
    pwfn: 510
  - name: w1cy
    desc: Sidebar, cyan
    cssf: W3.CSS
    pwfn: 510
  - name: w1te
    desc: Sidebar, teal
    cssf: W3.CSS
    pwfn: 510
  - name: w1grn
    desc: Sidebar, green
    cssf: W3.CSS
    pwfn: 510
  - name: w1lg
    desc: Sidebar, light green
    cssf: W3.CSS
    pwfn: 510
  - name: w1li
    desc: Sidebar, lime
    cssf: W3.CSS
    pwfn: 510
  - name: w1kh
    desc: Sidebar, khaki
    cssf: W3.CSS
    pwfn: 510
  - name: w1ye
    desc: Sidebar, yellow
    cssf: W3.CSS
    pwfn: 510
  - name: w1am
    desc: Sidebar, amber
    cssf: W3.CSS
    pwfn: 510
  - name: w1or
    desc: Sidebar, orange
    cssf: W3.CSS
    pwfn: 510
  - name: w1do
    desc: Sidebar, deep orange
    cssf: W3.CSS
    pwfn: 510
  - name: w1bg
    desc: Sidebar, blue grey
    cssf: W3.CSS
    pwfn: 510
  - name: w1br
    desc: Sidebar, brown
    cssf: W3.CSS
    pwfn: 510
  - name: w1gr
    desc: Sidebar, grey
    cssf: W3.CSS
    pwfn: 510
  - name: w1dg
    desc: Sidebar, dark grey
    cssf: W3.CSS
    pwfn: 510
  - name: w1bl
    desc: Sidebar, black
    cssf: W3.CSS
    pwfn: 510
  - name: w1w3
    desc: Sidebar, w3schools
    cssf: W3.CSS
    pwfn: 510
  - name: w6
    desc: Architect
    cssf: W3.CSS
    pwfn: 502
  - name: w5
    desc: Dark Portfolio
    cssf: W3.CSS
    pwfn: 503
  - name: w2
    desc: Interior Designer
    cssf: W3.CSS
    pwfn: 504
  - name: w3
    desc: Marketing
    cssf: W3.CSS
    pwfn: 505
  - name: w7
    desc: Parallax
    cssf: W3.CSS
    pwfn: 506
  - name: w4
    desc: Startup
    cssf: W3.CSS
    pwfn: 507
